# Generated by Django 4.2.2 on 2023-06-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='userid',
            new_name='useremail',
        ),
    ]
